name: Build and Publish (Alpha Release)
kind: pipeline
type: docker
trigger:
  branch:
    - alpha
    
environment:
  release_type: alpha
  DPKG_FRONTEND: noninteractive

steps:
  - name: build
    image: ubuntu
    commands:
      - scripts/build.sh
