name: Build and Publish
kind: pipeline
type: docker
environment:
  release_type: alpha
  DPKG_FRONTEND: noninteractive
  nexus_repository_password:
    from_secret: nexus_repository_password

steps:
  - name: build
    image: ubuntu
    commands:
      - scripts/build.sh
