---
name: Build and Publish Alpha
kind: pipeline
type: docker
environment:
  pkgname: mpm-alpha
  release-type: alpha
  nexus_repository_password:
    from_secret: nexus_repository_password
  DEBIAN_FRONTEND: noninteractive

triggers:
  event:
    - push
  branch:
    - alpha
  paths:
    - src/PKGBUILD
    - .trigger

steps:
  - name: build
    image: ubuntu
    commands:
      - scripts/build.sh
---
kind: signature
hmac: 4a54071bb7ba0d6e0d6004bdad2e3f1fe54a5686e7d73adb93c13e68cd9e113f

...
