kind: pipeline
type: docker
name: mpm - stable
trigger:
  event:
    - push
  branch:
    - stable
  paths:
    - PKGBUILD
    - .drone/trigger

steps:
  - name: build
    image: ubuntu
    commands:
      - export _release_type=stable
      - bash .drone/build.sh

  - name: publish
    image: ubuntu
    shell: bash
    environment:
      nexus_pass:
        from_secret: nexus_pass
    commands:
      - bash .drone/publish.sh

---
kind: pipeline
type: docker
name: mpm - alpha
trigger:
  event:
    - push
  branch:
    - alpha
  paths:
    - PKGBUILD
    - .drone/trigger

steps:
  - name: build
    image: ubuntu
    commands:
      - export _pkgname=mpm-alpha
      - export _release_type=alpha
      - bash .drone/build.sh

  - name: publish
    image: ubuntu
    shell: bash
    environment:
      nexus_pass:
        from_secret: nexus_pass
    commands:
      - bash .drone/publish.sh
