kind: pipeline
type: docker
name: build and publish
environment:
  release_type: alpha
  DPKG_FRONTEND: noninteractive

steps:
  - name: build
    image: ubuntu
    commands:
      - scripts/build.sh
