name: Build and Publish (Alpha Release)
kind: pipeline
type: docker
environment:
  release_type: alpha
  DPKG_FRONTEND: noninteractive

clone:
  - name: Clone

steps:
  - name: Build
    image: ubuntu
    commands:
      - scripts/build.sh
