name: Build and Publish (Alpha Release)
kind: pipeline
type: docker
environment:
  # PKGBUILD settings
  release_type: alpha
  # Settings for commands
  DPKG_FRONTEND: noninteractive
  # Secrets
  nexus_repository_password:
    from_secret: nexus_repository_password

steps:
  - name: build
    image: ubuntu
    commands:
      - scripts/build.sh
