kind: pipeline
type: docker
name: build and publish to repo
trigger:
  event:
    - push
  branch:
    - stable
  paths:
    - PKGBUILD

steps:
  - name: build
    image: ubuntu
    commands:
      - bash .drone/build.sh

  - name: publish
    image: ubuntu
    shell: bash
    environment:
      nexus_pass:
        from_secret: nexus_pass
    commands:
      - bash .drone/publish.sh

---
kind: pipeline
type: docker
name: build and publish to repo
trigger:
  event:
    - push
  branch:
    - alpha
  paths:
    - PKGBUILD

steps:
  - name: build
    image: ubuntu
    commands:
      - bash .drone/alpha.sh
      - bash .drone/build.sh

  - name: publish
    image: ubuntu
    shell: bash
    environment:
      nexus_pass:
        from_secret: nexus_pass
    commands:
      - bash .drone/publish.sh
