---
kind: pipeline
type: docker
name: Build and Publish (Alpha Release)
environment:
  test: testing
  pkgname: mpm\-alpha
  release_type: alpha
  nexus_repository_password:
    from_secret: nexus_repository_password
  DEBIAN_FRONTEND: noninteractive

trigger:
  event:
    - push
  branch:
    - alpha
  paths:
    include:
      - src/PKGBUILD
      - .trigger

steps:
  - name: build
    image: ubuntu
    commands:
      - scripts/build.sh
---
kind: signature
hmac: 7e43f689b59fafaed35c9468c978f298fba21ec012d682675fc7d479585a2784

...
