kind: pipeline
type: docker
name: mpm
volumes:
  - name: package directory
    temp: {}
trigger:
  event:
    - push

steps:
  - name: build
    image: ubuntu
    volumes:
      - name: package directory
        path: /tmp/mpm/package/
    commands:
      # INSTALL NEEDED PACKAGES
      - export DEBIAN_FRONTEND=noninteractive
      - apt-get update
      - apt-get dist-upgrade -y
      - apt-get install wget sudo -y
      # SET UP REPO AND INSTALL CURRENT COPY OF MAKEDEB
      - wget 'https://hunterwittenborn.com/keys/apt.asc' -O /etc/apt/trusted.gpg.d/hwittenborn.asc
      - echo 'deb [arch=all] https://repo.hunterwittenborn.com/debian/makedeb any main' | tee /etc/apt/sources.list.d/makedeb.list
      - apt-get update
      - apt-get install makedeb -y
      # CREATE BUILD USER
      - useradd -m user
      # SET FOLDER PERMS AND BUILD MPM
      - chown user:user /drone/
      - chown user:user /drone/src -R
      - sudo -u user makedeb
      # COPY MPM TO TEMP VOLUME FOR PUBLISH STEP
      - cp mpm*.deb /tmp/mpm/package/

  - name: publish
    image: ubuntu
    shell: bash
    volumes:
      - name: package directory
        path: /tmp/mpm/package/
    environment:
      nexus_pass:
        from_secret: nexus_pass
    commands:
      # INSTALL CURL
      - export DEBIAN_FRONTEND=noninteractive
      - apt update
      - apt dist-upgrade -y
      - apt install curl -y
      # PUBLISH PACKAGE TO REPOSITORY
      - package="$(ls /tmp/mpm/package/*.deb)"
      ## EXIT WITH CODE 1 IF MULTIPLE PACKAGES WERE LISTED IN PACKAGE DIRECTORY
      - if [ "$(echo $${package} | awk -F ' ' '{print $2}')" != "" ]; then exit 1; fi
      - |
        curl -u "system:$${nexus_pass}" -H "Content-Type: multipart/form-data" --data-binary "@$${package}" "https://nexus.hunterwittenborn.com/repository/mpm/"
