---
name: Build and Publish (Alpha Release)
kind: pipeline
type: docker
trigger:
  branch:
    - alpha
steps:
  - name: build
    image: ubuntu
    environment:
      pkgname: mpm-alpha
      release_type: alpha
    commands:
      - scripts/build.sh
