---
name: Build and Publish (Alpha Release)
kind: pipeline
type: docker
environment:
  release_type: alpha
  DPKG_FRONTEND: noninteractive
trigger:
  branch:
    - alpha
steps:
  - name: build
    image: ubuntu
    commands:
      - scripts/build.sh
