---
name: 'Build and Publish (Alpha Release)'
kind: pipeline
type: docker
environment:
  pkgname: mpm-alpha
  release-type: alpha
  nexus_repository_password:
    from_secret: nexus_repository_password
  DEBIAN_FRONTEND: noninteractive

triggers:
  event:
    - push
  branch:
    - alpha
  paths:
    - src/PKGBUILD
    - .trigger

steps:
  - name: build
    image: ubuntu
    commands:
      - scripts/build.sh
---
kind: signature
hmac: 27b0d7a98618be4dc225b287284afff98cc339afed62d098317119a48b1bb29f

...
