kind: pipeline
type: docker
name: mpm - stable
trigger:
  event:
    - push
  branch:
    - stable
  paths:
    - PKGBUILD
    - .drone/trigger

steps:
  - name: build
    image: ubuntu
    environment:
      _release_type: stable
    commands:
      - bash .drone/build.sh

  - name: publish
    image: ubuntu
    environment:
      nexus_pass:
        from_secret: nexus_pass
    commands:
      - bash .drone/publish.sh

---
kind: pipeline
type: docker
name: mpm - alpha
trigger:
  event:
    - push
  branch:
    - alpha
  paths:
    - PKGBUILD
    - .drone/trigger

steps:
  - name: build
    image: ubuntu
    environment:
      _pkgname: mpm-alpha
      _release_type: alpha
    commands:
      - bash .drone/build.sh

  - name: publish
    image: ubuntu
    environment:
      nexus_pass:
        from_secret: nexus_pass
    commands:
      - bash .drone/publish.sh
