---
name: Build and Publish (Stable Release)
kind: pipeline
type: docker
environment:
  # PKGBUILD variables
  release_type: stable
  FUNCTIONS_DIR: /usr/lib/mpm
  REPO_DIR: /etc/mpm/repo
  # Secrets
  nexus_repository_password:
    from_secret: nexus_repository_password
  # Other stuff
  DEBIAN_FRONTEND: noninteractive
trigger:
  branch:
    - stable
steps:
  - name: build
    image: ubuntu
    commands:
      - scripts/build.sh

  - name: publish
    image: ubuntu
    commands:
      - scripts/publish.sh

---
name: Build and Publish (Alpha Release)
kind: pipeline
type: docker
environment:
  # PKGBUILD variables
  release_type: alpha
  FUNCTIONS_DIR: /usr/lib/mpm
  REPO_DIR: /etc/mpm/repo
  # Secrets
  nexus_repository_password:
    from_secret: nexus_repository_password
  # Other stuff
  DEBIAN_FRONTEND: noninteractive

trigger:
  branch:
    - alpha
steps:
  - name: build
    image: ubuntu
    commands:
      - scripts/build.sh

  - name: publish
    image: ubuntu
    commands:
      - scripts/publish.sh
