---
name: Build and Publish (Alpha Release)
kind: pipeline
type: docker
trigger:
  branch:
    - alpha
steps:
  - name: build
    image: ubuntu
    environment:
      # PKGBUILD variables
      release_type: alpha
      FUNCTIONS_DIR: /usr/lib/mpm
      REPO_DIR: /etc/mpm/repo
      # Other stuff
      DEBIAN_FRONTEND: noninteractive
    commands:
      - scripts/build.sh

  - name: publish
    image: ubuntu
    environment:
      nexus_repository_password:
        from_secret: nexus_repository_password
      DEBIAN_FRONTEND: noninteractive
    commands:
      - scripts/publish.sh
